# Generated by Django 5.2.4 on 2025-07-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('title', 'description')},
        ),
    ]
