# Generated by Django 5.2.4 on 2025-07-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Online', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(default='https://example.com/register'),
            preserve_default=False,
        ),
    ]
